### ISSUE TITLE
Why is there a warning of using hmac-sha2-512/256?

### ISSUE THREAD

**Issue by mpet** [jtesta/ssh-audit#140]
Hi,

We had some guys in our project running an audit with this tool. They got the following message.

![image](https://user-images.githubusercontent.com/1445826/174967419-0d203455-ace6-419b-b08b-8351b8f11597.png)

Now they want to remove the support for these MAC algorithms. Could you explain why these algorithms are not secure? I googled it and could not find any facts supporting it. 

br,

//mike

**Comment by egberts** [comment]
SHA2 is like a either-OR algorithm and one of its digest algorithms is weaker enough to fit the audit of “weak”.

**Comment by mpet** [comment]
Where is the common consensus for this opinion? Which digest algorithm are you referring to? Where can I read about it?

**Comment by egberts** [comment]
SHA-2 is a 21 year old standard.  And is easily collided. 

https://eprint.iacr.org/2011/286.pdf

**Comment by severach** [comment]
Years of research have shown that IPSec's choice of [EtM](https://crypto.stackexchange.com/questions/202/should-we-mac-then-encrypt-or-encrypt-then-mac) is the only secure way. 

Though the command line colors -etm MAC green, the website colors -etm black. That's because ctr-etm is secure but is going away for something better. TLS 1.3 is going to AEAD only and your SSH servers should too. No more roll your own encryption from buckets of ciphers and MACs. The future is all aes-gcm and chacha20-poly1305 where the advertised MAC are no longer relevant.

**Comment by jtesta** [comment]
Thanks @egberts , @thecliguy , and @severach for helping with this question!
