### ISSUE TITLE
-ssh-rsa is marked with Red color but in server config I did not found it

### ISSUE THREAD

**Issue by jatpat** [jtesta/ssh-audit#147]
Hi,

I tested my sftp server and found that **-ecdsa-sha2-nistp256**  and **-ssh-rsa**  algorithms are marked with Red color in test output, but when I check in config file on server, I did not found any of them algorithm in the list.

I have attached scrrenshots.

**Test output:**

![image](https://user-images.githubusercontent.com/6779382/192214133-0bc65009-10e5-4bcf-88c3-beed4702df7a.png)

Server config file:
![image](https://user-images.githubusercontent.com/6779382/192214313-41a7edf7-430b-4659-ab3a-700134265fa7.png)

**Comment by egberts** [comment]
`-ssh-rsa` has been obsoleted and is no longer found in OpenSSH v8.7+

And `ecdsa-sha2-nistp256` is on the way out since v7.6.  Also Oracle and SFTP has problem with this last July 2022. 

https://stribika.github.io/2015/01/04/secure-secure-shell.html

**Comment by jatpat** [comment]
That is understood and fine with that, but I have question here that why ssh-audit tool is showing **-ecdsa-sha2-nistp256** and **-ssh-rsa** algorithms which are not listed in server config file.

**Comment by jatpat** [comment]
hi @thecliguy ,

Thank you for reply.

**Comment by thecliguy** [comment]
Hello @jatpat 

If you want to retain `rsa-sha2-256` & `rsa-sha2-512`, and eliminate the use of `ssh-rsa` and `ecdsa-sha2-nistp256` (which are marked as "fail" on the audit), then:
  * Add this to your config file: `HostKeyAlgorithms rsa-sha2-256,rsa-sha2-512`
  * Restart the SSH server service.
  * Re-run ssh-audit.
  
But before you do any of this, make sure that the client software you use to connect to your SFTP server is capable of negotiating `rsa-sha2-256` and/or `rsa-sha2-512`, otherwise you run the risk of not being able to connect to the server once the changes have been made.

**Comment by jtesta** [comment]
Thanks for answering this, @thecliguy !
