### ISSUE TITLE
automatic re-generation of host keys

### ISSUE THREAD

**Issue by XSpielinbox** [jtesta/ssh-audit#167]
The RedHat Enterprise Linux 7 Server / CentOS 7 Server Guide has a section about Disabling automatic re-generation of ECDSA keys.

This should be added to all other Guides too:
In Fedora one must mask the corresponding service (`systemctl mask sshd-keygen@ecdsa`) (I assume that it is the same on newer RHEL versions).
In OpenSUSE one must set `SSHD_AUTO_KEYGEN` to `no` in `/etc/sysconfig/ssh`.
On Debian/Ubuntu limiting the algorithms via HostKeyAlgorithms is enough for restarts, but during package reinstalls or upgrades it re-generates  ECDSA keys. I haven't found a good way to prevent that yet. Any ideas/help would be highly appreciated.
My current workaround is to generate a ECDSA Key with maximum length (at the time of writing 521 bits), which prevents this regeneration of weaker keys. Alternatively, just having two empty files with the name of the ECDSA key also prevents this regeneration, though I don't know what unforeseen behavior this may cause.

**Comment by jtesta** [comment]
Do those OSes only regenerate ECDSA keys?  The hardening guides disable ECDSA; only ED25519 and RSA remain enabled.

I've noticed that ECDSA keys get re-created at times, though this has never created an issue, since its corresponding `HostKey` directive is disabled.  The keys just sit on the disk, unused.
