### ISSUE TITLE
Update Debian Manpage

### ISSUE THREAD

**Issue by jtesta** [jtesta/ssh-audit#173]
The Debian package currently includes an alternate (and very bare) manpage.  I submitted PRs for their `master` and `debian/sid` branches to switch over to our more complete manpage instead:
* https://salsa.debian.org/debian/ssh-audit/-/merge_requests/2
* https://salsa.debian.org/debian/ssh-audit/-/merge_requests/3

We can use this issue to track the status of the Debian package.

**Comment by williamdes** [comment]
Hi !

Debian maintainer here, randomly found this projected and checked it was packaged.
It is, so very cool !
Can you add a line for that on the README ?
```sh
apt-get install ssh-audit
```

Tested Debian 12 `debian/sid`  and it works fine !

Good job coordinating with Debian on Salsa 👍🏻 

That said since Debian 12 is in freeze mode the manpage change will wait for Debian to be release so it get's out to sid.
Next Debian version then. But if the maintainer does backports it could get to Debian 12 users.

Anyway, be sure to keep an eye on https://tracker.debian.org/pkg/ssh-audit

**Comment by jtesta** [comment]
Thanks for the info, @williamdes !

Looks like my patch to the `debian/sid` branch was merged!  The other one to `master` was not yet merged, however...

**Comment by williamdes** [comment]
> Thanks for the info, @williamdes !
> 
> Looks like my patch to the `debian/sid` branch was merged! The other one to `master` was not yet merged, however...

Awesome!
Well, I am not sure if it will get merged
Debian sid will be the next Debian after the one pending release right now
So maybe it can be closed, Ileave this up to you

Have a nice day

**Comment by williamdes** [comment]
> The target branch master does not exist. 

You can definitely close it

**Comment by jtesta** [comment]
Looks like the maintainer's `master` branch was deleted some time in the last hour!  I suppose we've done everything we can at this level to get Debian's man page up to date; now its just a waiting game for the next release.
