### ISSUE TITLE
Test all RSA host key types individually

### ISSUE THREAD

**Issue by jtesta** [jtesta/ssh-audit#179]
Currently, the code only tests one host key in the family of RSA host keys.  The rationale was that, say, a 2048-bit key found against `rsa-sha2-256` would also apply to `rsa-sha2-512`.  Fixing the key size would fix all the RSA host key types simultaneously.

However, this strategy results in strange output.  `rsa-sha2-256` would get flagged with a warning, but `rsa-sha2-512` would appear in green.  Seems like the fix would be to test all host keys individually; this would cause all errors & warnings to be tagged correctly.

**Comment by thecliguy** [comment]
The only reason I can think of to scan each RSA signature algorithm type individually in order to obtain the RSA key size would be to satisfy the existing logic of the code. Personally, I don't think that's a good enough reason to make extra calls against a target SSH server...

I think that ssh-audit should endeavour to keep the number of calls against a target SSH server to a minimum because it's not uncommon for a server to enforce rate control. The more calls that ssh-audit makes against a server in quick succession, the more likely it is to trigger rate control and result in a scan being blocked before completion.

So, I'd suggest sticking to a single call to obtain the RSA host key size and fixing the code so it doesn't produce confusing output when a server is encountered that supports multiple RSA signature algorithms.

To be clear - there's no such a thing as a _"family of RSA host keys"_, there's just the one RSA host key type but there are multiple RSA signature algorithms (`ssh-rsa`, `rsa-sha2-256` and `rsa-sha2-512`).

**Comment by thecliguy** [comment]
@jtesta : I think this patch for `perform_test` in `hostkeytest.py` solves the problem... 

If the current host key that's just been scanned is a member of the `RSA_FAMILY` then duplicate it in `SSH2_KexDB.ALGORITHMS` for all RSA host key types.

```python
# If this host key type is in the RSA family, then mark them all as parsed (since results in one are valid for them all).
if host_key_type in HostKeyTest.RSA_FAMILY:
    for rsa_type in HostKeyTest.RSA_FAMILY:
        host_key_types[rsa_type]['parsed'] = True
        SSH2_KexDB.ALGORITHMS['key'][rsa_type] = SSH2_KexDB.ALGORITHMS['key'][host_key_type]
else:
    host_key_types[host_key_type]['parsed'] = True
```

What do you think?

**Comment by jtesta** [comment]
@thecliguy : If that works in testing, then sure!  Feel free to submit a PR, if you have the spare time.

**Comment by thecliguy** [comment]
Classic rubber duck debugging... As I submitted that comment I realised that this isn't quite the right solution... But I think it's pretty close...

I realise now that we can't simply duplicate an RSA host key DB record in its entirety because it may have comments associated with it that don't apply to every other RSA key type. We only want to duplicate the key size.

I'll fine-tune this idea a bit further and submit a proper PR once its ready.

**Comment by thecliguy** [comment]
@jtesta : I've pretty much finished writing a working patch for this now. I just need to do a bit more testing.

When are you planning to release v2.6.0? I only ask because I'll try and submit the PR before you make the release.

**Comment by jtesta** [comment]
I just have some testing and a little debugging to do.  Depending on
how that goes, the new release could be ready in 24-48 hours!

**Comment by thecliguy** [comment]
Thanks for confirming, I'll try and get a PR submitted before then.

I've a question for you...

The `ALGORITHMS` data structure in `ssh2_kexdb.py` consists of an algorithm name followed by four fields:

1. `version_first_appeared_in`
2. `failure`
3. `warning`
4. `info`

My patch needs to write to a record's `failure` and/or `warning` field. 

The problem is that not all records in `ALGORITHMS` have these fields at present and I'd like to avoid having to write code to detect if a field is not present and add it...

So, at a minium I will need to update all RSA family members in `ALGORITHMS` to include a `version_first_appeared_in`, `failure` and `warning` field.

Are you happy with this minimal approach, or would you prefer that every single record in `ALGORITHMS` is fully populated wth a `version_first_appeared_in`, `failure`, `warning` and `info` field?

**Comment by jtesta** [comment]
The minimal approach would be fine.

I've been dreaming of re-working that database structure and parsing ever since I took maintainership.  Its a mess.  But that's a task for another day...

**Comment by thecliguy** [comment]
OK, let me take a look...

**Comment by thecliguy** [comment]
@jtesta : I've revised #182 as suggested. 

How does it look to you?

**Comment by thecliguy** [comment]
Sorry, just make a couple of small corrections. That's it, I'm done now. Over to you...

**Comment by jtesta** [comment]
@thecliguy : merged your PR.  Thanks!!
