### ISSUE TITLE
more concise  [info] phrasing for all

### ISSUE THREAD

**Issue by perkelix** [jtesta/ssh-audit#253]
We currently have e.g.
```
-- [info] available since OpenSSH 6.5
`- [info] default cipher since OpenSSH 6.9
```
or
```
-- [info] available since OpenSSH 7.4, Dropbear SSH 2018.76
`- [info] default key exchange since OpenSSH 6.4
```
A more concise format would be:
```
-- [info] available since OpenSSH 6.5; default since OpenSSH 6.9
```
or
```
-- [info] available since OpenSSH 7.4, Dropbear SSH 2018.76; default since OpenSSH 6.4
```
Generally-speaking, long [info] lines should be avoided and instead refer to footnotes in `# additonal info` instead.

**Comment by jtesta** [comment]
Is this the same as #202 ?

**Comment by perkelix** [comment]
> Is this the same as #202 ?

No, this one is a general request. Others are more specific.

**Comment by jtesta** [comment]
I think this comes down to personal preference.  My own preference is to leave it as-is, but perhaps we can let the community vote on this.

If anyone would like this change made, put a thumbs-up emoji on this comment.  Otherwise, if you'd like the output format to remain as-is, put a thumbs-down emoji on this comment.  Voting will remain open until Oct. 1 (for approximately 3 months).  After that time, I'll follow whatever the community prefers.

**Comment by jtesta** [comment]
As per the results of the community vote (1 in favor, 2 against), no changes will be made to the `info` line formatting.
