### ISSUE TITLE
 more concise phrasing for (kex) ext-info-s [info]

### ISSUE THREAD

**Issue by perkelix** [jtesta/ssh-audit#256]
What we currently have:
```
(kex) ext-info-s                          -- [info] pseudo-algorithm that denotes the peer supports RFC8308 extensions
```
What I recommend instead:
```
(kex) ext-info-s                          -- [info] supports RFC8308 extensions
```

**Comment by jtesta** [comment]
I think mentioning that `ext-info-s` is not a real key exchange algorithm is important.  I don't know of a way to use less characters to convey the same level of meaning.

**Comment by perkelix** [comment]
I don't see why that aspect is so important. 

Bttw, according to [this](https://www.openssh.com/specs.html), support for `ext-info-c` was also added. Do we test for this?

**Comment by jtesta** [comment]
> Bttw, according to this, support for ext-info-c was also added. Do we test for this?

Yes.

**Comment by jtesta** [comment]
I think this comes down to personal preference. My own preference is to leave it as-is, but perhaps we can let the community vote on this.

If anyone would like this change made, put a thumbs-up emoji on this comment. Otherwise, if you'd like the output to remain as-is, put a thumbs-down emoji on this comment. Voting will remain open until Oct. 1 (for approximately 3 months). After that time, I'll follow whatever the community prefers.

**Comment by jtesta** [comment]
As per the results of the community vote (1 in favor, 3 against), no changes will be made to the `ext-info-s` description.
