### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration (with --json, and Python 3.8)

### ISSUE THREAD

**Issue by moreati** [jtesta/ssh-audit#49]
Running with `-j` or `--json` with Python 3.8.x cause the following error

```
± ./ssh-audit.py -j raspberrypi2.local
Traceback (most recent call last):
  File "./ssh-audit.py", line 3350, in <module>
    main()
  File "./ssh-audit.py", line 3347, in main
    audit(conf)
  File "./ssh-audit.py", line 3337, in audit
    print(json.dumps(build_struct(banner, kex=kex, client_host=s.client_host), sort_keys=True))
  File "./ssh-audit.py", line 3245, in build_struct
    for host_key_type in host_keys.keys():
RuntimeError: dictionary keys changed during iteration
```

The code in question is

https://github.com/jtesta/ssh-audit/blob/e447c42a79df49841d5269eacde6dbeb811a6be4/ssh-audit.py#L3245-L3249

The fix for the immediate is straightforward, replace `host_keys.keys()` with `list(host_keys.keys())` so the loop iterates over a copy.

However, I'm concerned about the rest of the loop. I think its
 - picking one rsa host key amongst (possibly) several, and discarding any others
 - the key it keeps is not predictable, because iteration over dict keys is non-deterministic in Python 3.5 and earlier.

I need to confirm whether an ssh server can have multiple RSA keys (perhaps with different key lengths).

Other details

```
± python3 --version
Python 3.8.2
± git show --summary | cat
commit e447c42a79df49841d5269eacde6dbeb811a6be4
Author: Joe Testa <jtesta@positronsecurity.com>
Date:   Wed Mar 11 11:55:14 2020 -0400

    Bumped version to v2.2.0.
```

**Comment by moreati** [comment]
Based on some adhoc trials, OpenSSH 7.9p1 accepts multiple `HostKey` lines referring to rsa keys, but it only uses the first one that is mentioned, e.g.

```
pi@raspberrypi2:/etc/ssh $ grep HostKey sshd_config
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_rsa_key_4096
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
pi@raspberrypi2:/etc/ssh $ ssh-keyscan -t rsa localhost
# localhost:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
localhost ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpiBNH65dEgB3MVUUZyqscxp650ubkY0cXNwcvaQmqC1uJ9405NFOfXtnd3mIYrjfTxFqVy1vUZUT+NwCADUeFNz5r8DqdiPRhy5MNuEaTkbsYQ1QEw4b8yc8RJitynxKNKesXgSDEta/cMSFbQL2Obj6yuUaUFUuAfFRv91kAso/m888JPNjHrnfiNuKpruxrlYGjtrDCHtFDCK+dpud9kB2E3wzKDWHgPp0y03cRhfYCc9e3sgSCDIDYxHx6EwmPx/O6DxgG+16WFWR93Hr3RZdek//e2VxqLbxvzRy6a6j4to8TnxVptaFyqLP3AtQk7dMhIg1nEuuXOovNi4xb
```
then swap the lines, restart sshd, and scan again

```
pi@raspberrypi2:/etc/ssh $ grep HostKey sshd_config
HostKey /etc/ssh/ssh_host_rsa_key_4096
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
pi@raspberrypi2:/etc/ssh $ ssh-keyscan -t rsa localhost
# localhost:22 SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
localhost ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAFfww89THHrY2taUqUvwtjcT4c/Zvm30l+/WUyYm7Q8ekDN9xnGGeVN3b85M9tb3LitSC0ZIn/2SySa6/lSZ+1Cc239jog7e2UJ3KIjgz4T7Z+1cPu1f8afiW0GtE1/GnJ7f31qFuqI4wCA0a0z8r5EmthI/Xod/g/RdSXXW8H208D+qQZJZvyfG1qcyjhPIxvOjRMrQsP2donCGMAuWU5VyUWsbx9wtgH6kU/XUltRzTaKNk5l8xWw0xRoq9RAcA28xq7go1Y8/HzeahCN0jUrmivU5/FoJH5+rwRky+gCq/4UWB57DsQYuXSF04TOTEtJBGXJ2PEsW1TYiVUNAnXk+NhdjXUjI99/fLTkuZinj4ykIcucYEhHDE4XtbBTedFV6ugY9JFXRQfk7riFIEsvCqdY37NjsVB02JzLFk7RM91kMYr1XUwIJTDRn9JAZbdHIl7tElF5lh3njPfz2DZItOclYVr+hQ5WL7K5X7Meqjr1cgYU9OfbOJqVxdUnMVIQKNZ6vbB6JwfHPzG9Ol0SA6Kx5R0B1YtA/GT/FbJuWMjRUnZtesIp56XOIsqL58Ntfraf5YCxQsoyMIwtlWpQsMRYv6hZDK7MeTDnMy6KzZF4MWILYLQKnn4gOWvn2OI/WXFZ3h1Ost0dbnnbtqNKoUIlVkVStZelqWQoLA3Q==
```

That would suggest the for loop is good enough as is.

**Comment by jugmac00** [comment]
Hi @moreati 

thanks for your bug report.

This has been already reported in #41 and fixed in #44.

Unlike most other open source projects, here a long running dev branch is used for the time between releaeses.

I still think it would be a great idea to merge every accepted and well tested pull request to master.

**Comment by moreati** [comment]
Do you have any thoughts on the other possible bug? That if an SSH server offered multiple RSA keys, ssh-audit would pick one at random.

**Comment by jugmac00** [comment]
Well, while I contributed some bug fixes, fixed the test runner, fixed most type annotations..., in my "real" life I am a professional Python programmer in a complete other domain. I just found this project when I had to setup some Ubuntu boxes and I wanted to harden the SSH access. Actually, I started contributing not only because I love open source and I love to give something back, I also try to learn more about SSH.

Back when I fixed the `RuntimeError` I certainly also had a look at what the code actually does, or intends to do.

The code collapses all ssh-rsa keys (from this RSA_FAMILY) into one - and yes, due to not guaranteed sort order until Python 3.7 (in Python 3.6 it was not guaranteed, but an implementation order) this does not look like it is deterministic.

I also do not understand the comment above the code completely. If I want guaranteed order in a dict before Python 3.7, I'd use an `OrderedDict`. Also, I did not have a look at the newly introduced Docker testing framework.

I just recently installed Python 3.5, only because this project still supports it, and Python 3.5 is "special" when you try to type annotate a project.

So, strictly from my personal point of view - I neither use the JSON output nor I ever used Python 3.5 - except for type annotating this project.

I guess this possible problem is something you have to discuss with @jtesta, as he is the maintainer of this project, has the domain knowledge and also is the one who decides when to drop support for Python 3.5.

**Comment by jtesta** [comment]
> Do you have any thoughts on the other possible bug? That if an SSH server offered multiple RSA keys, ssh-audit would pick one at random.

@moreati Sorry for the very late response.  I got side-tracked in life a bit.

The way I've seen servers implement multiple RSA host key types is that there is only _one_ RSA key, but encoded and hashed in different ways.  So for example, if a server supports `ssh-rsa`, `rsa-sha2-256`, and `rsa-sha2-512`, they are all derived from the same raw key material, but are hashed with SHA-1, SHA-256, and SHA-512, respectively.  Hence, the program will treat any one key type as the definitive answer for all of them.

Does this answer your question?  And are you still running into any bugs in the `dev` branch?

**Comment by moreati** [comment]
> Does this answer your question?

Well enough. I'd more-or-less concluded that multiple RSA keys might be possible according to the protocol, but rarely (if ever) seen in the wild

> And are you still running into any bugs in the dev branch?

No, thank you.
